#ifndef ACTOR_COMPONENT_DEFINITIONS_H
#define ACTOR_COMPONENT_DEFINITIONS_H

/*
    The default types of actors available.
*/
enum DEFAULT_ACTOR_TYPES {
    ACTOR_EMPTY,
    ACTOR_STATIC,
    ACTOR_STATE_BLOCK,
    ACTOR_ENEMY,
    ACTOR_PLAYER,
    ACTOR_LANTERN,
    ACTOR_COMPLETE_CHECK,
    ACTOR_SIGNPOST,
    ACTOR_DEATHTOUCH,
    ACTOR_MOVE_LOOP,
};
#endif